// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm2uTbYsiZ3piyYFvTP-pjZn7JQCfItys',
    appId: '1:270716777811:web:24dff7f845fe67f5241da6',
    messagingSenderId: '270716777811',
    projectId: 'venue-vibes',
    authDomain: 'venue-vibes.firebaseapp.com',
    storageBucket: 'venue-vibes.appspot.com',
    measurementId: 'G-EKNC2N4PBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQ0YUrxdlbqkra7COiHsB8nGxfOS-GIk',
    appId: '1:270716777811:android:c2621d1b5c1b2a38241da6',
    messagingSenderId: '270716777811',
    projectId: 'venue-vibes',
    storageBucket: 'venue-vibes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4GJ748p1AHeJtFAuVg1pI0vkaYCAQCg',
    appId: '1:270716777811:ios:07bf57e67b365463241da6',
    messagingSenderId: '270716777811',
    projectId: 'venue-vibes',
    storageBucket: 'venue-vibes.appspot.com',
    iosBundleId: 'com.example.venueVibes',
  );
}
